### ISSUE TITLE
pufferd should follow 301 and 302 redirects

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/pufferd#35]
When talking to the auth server, pufferd does not follow 301 and 302 redirects, and instead just errors out

**Comment by LordRalex** [comment]
We cannot follow 301/302, as this would in the end go against the http codes, which only GET and HEAD should follow 301/302 automatically.

https://stackoverflow.com/a/27505136

As such, I will have to avoid doing this myself, since it would not make sense to then violate the standard. Arguably, it throwing an error is good, since who knows what is going wrong if there's a 301/302 in place.
