### ISSUE TITLE
File uploading issue

### ISSUE THREAD

**Issue by abates** [PufferPanel/pufferd#44]
PR #43 changed some logic with respect to file uploads.  There was concern with introducing a breaking change to [PufferPanel/app/views/node/files/index.html#L293](https://github.com/PufferPanel/PufferPanel/blob/master/app/views/node/files/index.html#L293
).  Despite the concerns, the PR was merged.

However, the PR did in fact break file editing.  As it turns out, PufferPanel is never passing the noform query parameter on to pufferd.  Therefore, the noform conditional is **always** false at [routing/server/server.go#L297](https://github.com/PufferPanel/pufferd/blob/master/routing/server/server.go#L297)

I think the logic in pufferd is correct and that PufferPanel needs to be updated to send the noform query parameter.  The alternative is to do away with the noform query parameter completely and simply look at the request

```go
  var sourceFile io.ReadCloser

  if sourceFile, _, err = c.Request.FormFile("file"); err == gohttp.ErrNotMultipart {
    sourceFile = c.Request.Body
  }

  _, err = io.Copy(file, sourceFile)
```

I've tested the above code against the current PufferPanel head and it works for both file uploads and file edits with no required changes to the PufferPanel code.

Please let me know if this is an acceptable solution and I will generate a PR.

**Comment by abates** [comment]
I can create a pull request if this is an acceptable solution.

**Comment by abates** [comment]
Actually, further testing revealed that my proposed solution was not quite working.  This code appears to work correctly:

```go
  v := c.Request.Header.Get("Content-Type")
  if t, _, _ := mime.ParseMediaType(v); t == "multipart/form-data" {
    sourceFile, _, err = c.Request.FormFile("file")
  } else {
    sourceFile = c.Request.Body
  }
```

**Comment by LordRalex** [comment]
I actually do like that solution better, since it's working with the request and not needing anything fancy.

If that works correctly, please submit a PR for it, thanks!

I do need to see though why it wasn't passing the flag, because I implemented that change because of something using a form and had tested it (I had spent a bit of time on it so I swore I made sure it worked).

**Comment by abates** [comment]
This is the offending line in PufferPanel:

[src/routes/daemon/routes.php#L129](https://github.com/PufferPanel/PufferPanel/blob/master/src/routes/daemon/routes.php#L129)

The query portion of the URL is being built rather than being passed on and there is no logic to add 'noform' even if it is in the original query string.

**Comment by LordRalex** [comment]
Oh, I understand why I did it that way at the time.

There's 2 calls to a save method, and they come from 2 source:
1) The upload manager, which is a library we use, and I believe uses form to submit the files
2) The file editor, which is mostly our code for the actual data we send in.

So, the fix we'd make would fix one, but then break the other. The solution you proposed here, if it does work, should actually handle both cases, since we now rely on the header.

**Comment by LordRalex** [comment]
That's also a good catch, I forgot klein won't include the query string into the path.

I still like the fix that you made here instead, since it removes that need, although we will have to put a separate issue in to make sure that call functions correctly.

(I did my testing on a slightly older panel version and pufferd version, since those are in my prod environment, but those methods have not changed)
